server:
  port: 8888
spring:
  application:
    name: MyStore
  datasource:
    url: jdbc:postgresql://localhost:5432/mystore?serverTimeZone=America/São_Paulo
    username: postgres
    password: postdba
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true


